Add Admin Settings
HSFD-WS-24-25/appointment-organizer-frontend pull request #21
Opened 2024-11-19 07:59 UTC by marvinrentsch

2024-11-19 09:10 UTC, Mac10goesBRRRT commented
Spricht etwas dagegen, das selbe Settings-Panel für Admin bzw. User zu verwenden? Dann würde man sich doppelte Arbeit sparen. Du hast hier ja schon mehr gemacht als in der aktuellen User-Version

2024-11-19 11:30 UTC, marvinrentsch commented
Da spricht nichts dagegen. Dann würde ich das Settings-Panel vom Admin für Admin und User verwenden. Das passt ja für beide.

2024-11-20 18:14 UTC, MBKGuy approved these changes

2024-11-20 18:19 UTC, Mac10goesBRRRT requested changes

2024-11-20 18:19 UTC, Mac10goesBRRRT commented on app/components/AdminSettings.js
> +                    <Box sx={{ '& > :not(style)': { m: 1, width: '25ch' }, flex: 1, display: "flex", justifyContent: "center" }}>
Hier Meiner Meinung nach sinnvoll, Code-Duplikation noch zu minimieren. Du kannst innerhalb einer Komponente/Seite weitere die Komponenten definieren und auch nutzen.
Hier auch mal drauf achten, die Felder haben den selben value, ändern also gerne mal unbeabsichtigt andere Felder ab

2024-11-29 10:34 UTC, closed without merging