Add Participants List
HSFD-WS-24-25/appointment-organizer-frontend pull request #40
Opened 2024-11-25 13:27 UTC by marvinrentsch

2024-11-29 15:07 UTC, Mac10goesBRRRT requested changes
Sollte am besten unter events/[event-id]/participant-list/ liegen

2024-11-29 15:11 UTC, Mac10goesBRRRT commented
@CeloKr bitte schau mal, ob die neuen Komponenten verwendet werden

2024-11-29 18:48 UTC, CeloKr commented
@Mac10goesBRRRT Componente wurden verwendet, Kann man so übernehmen. @marvinrentsch,
bitte noch überlegen wie man auf die Seite kommt gegenfalls anpassen

2024-11-30 16:32 UTC, EricBergstreisser requested changes
Bitte diese pull-request mit einem Issue verbinden, welches aus einem Backlog-Item erstellt wurden, damit man versteht, welche Funktionalität damit umgesetzt werden soll.
Außerdem wäre es sehr hilfreich, wenn die pull-request eine ordentliche Beschreibung bekommt.

2024-12-02 12:52 UTC, CeloKr submitted a review, later dismissed
von meiner seite aus ok.

2024-12-02 15:08 UTC, EricBergstreisser reviewed
aktuell kommt man per Interface noch nicht auf die Seite, sondern nur per URL. Wie sorgen wir dafür, dass diese Seite nicht vergessen wird und jemand eine zweite erstellt. 

Als Backlog Item, dass sich jemand um die Einbindung kümmert?

2024-12-04 14:20 UTC, EricBergstreisser requested changes
Bitte diesen pull-request auf den neuen development-branch verschieben und schauen, ob er mit der neuen Ordnerstruktur klarkommt.

2024-12-08 10:03 UTC, Mac10goesBRRRT approved these changes
Von mir aus passt das

2024-12-09 13:57 UTC, EricBergstreisser approved these changes

2025-02-04 16:22 UTC, closed without merging