Users (without Token)
HSFD-WS-24-25/appointment-organizer-frontend pull request #44
Opened 2024-11-27 00:11 UTC by CeloKr

Userlist from Database to Frontend

Put, Get, Post, Delete voll funktionsfähig

2024-11-27 14:56 UTC, Mac10goesBRRRT commented
was muss ich dazu denn im backend alles machen?

2024-11-27 21:11 UTC, CeloKr commented
das mit dem Token geht nicht, einfach diese verbindung zwischen Frontend und Backend machen. 
Bei mir ging es wenn ich den Token umgangen habe, 
Ansonsten Funktioniert es genau wie es soll. nur die Verbindung der Datenbank mit dem Frontent spinnt.

2024-11-29 12:07 UTC, Mac10goesBRRRT requested changes

2024-11-29 12:07 UTC, Mac10goesBRRRT commented on app/admin/users/page.js
> +  // Benutzer abrufen
Hier hatte ich eine fertige Funktion, die auch auth für euch übernimmt. in der page.jsx ist die noch zu finden. Die Funktion erlaubt außerdem die Methode festzulegen, solte also auch CRUD funktionieren

2024-12-04 14:02 UTC, closed without merging