Nur noch eine Sidebar / SidebarStyle aufgeteilt -- Wartungsfreundlicher
HSFD-WS-24-25/appointment-organizer-frontend pull request #58
Opened 2024-11-29 20:57 UTC by CeloKr

2024-11-30 16:11 UTC, EricBergstreisser requested changes
Sieht gut aus. Genauso wie auch im Unterricht besprochen. 
Frage: Wird das viele Konflikte geben mit den Anderen, die noch die alte Version vom main gepullt haben?

2024-11-30 19:15 UTC, CeloKr commented
Es sollte eigentlich keine Konflikte geben.

Beschreibung füge ich hinzu.

2024-12-02 07:15 UTC, EricBergstreisser reviewed
jetzt wo du es in der Beschreibung erklärt hast, kann ich erkennen was du gemacht hast. Wäre es nicht sinnvoller ein switch-case zu machen? Wäre performanter und als default hättest du eine Error-Message oder so?

2024-12-02 07:42 UTC, Mac10goesBRRRT commented on app/components/Sidebar.js
> +  // Gemeinsame Menüeinträge
Das kann noch raus, ist ja mit `<SidebarLogInOut expanded={isExpanded}/>` schon erledigt

2024-12-02 08:35 UTC, CeloKr commented on app/components/Sidebar.js
> +  // Gemeinsame Menüeinträge
Wurde angepasst.

2024-12-02 11:13 UTC, EricBergstreisser approved these changes
Passt so 👍
Wird eine große Verbesserung für unseren Code und eine Erleichterung für die Zukunft sein.

Unbedingt mindestens 40 Minuten warten, nach dem letzten Merge auf main! Nicht mehrere pull-requests gleichzeitig mergen!
Danke

2024-12-02 11:44 UTC, merged