Add an event editer
HSFD-WS-24-25/appointment-organizer-frontend pull request #81
Opened 2024-12-11 18:40 UTC by DHaytham

2024-12-11 19:13 UTC, CeloKr commented
kannst du bitte noch eine beschreibung hinzufügen, damit wir wissen was es ist. Am besten noch ein Isue dazu verbinden

2024-12-11 20:09 UTC, DHaytham commented
> kannst du bitte noch eine beschreibung hinzufügen, damit wir wissen was es ist. Am besten noch ein Isue dazu verbinden

ist jetzt erledigt :)

2024-12-12 21:37 UTC, Mac10goesBRRRT requested changes
Beide Seiten sind meiner Meinung nach evtl besser in _/event/[event-id]/editEvent_ bzw. _/event/[event-id]/preview_ aufgehoben

2024-12-12 21:37 UTC, Mac10goesBRRRT commented on app/[instanz]/[organisation]/[user]/editEvent/page.js
> +            }}
Können wir hier nicht die styledComponents verwenden?

2024-12-12 21:37 UTC, Mac10goesBRRRT commented on app/[instanz]/[organisation]/[user]/preview/page.js
>                      Bearbeiten
Der Link führt zu einem 404

2024-12-12 21:37 UTC, Mac10goesBRRRT commented on app/[instanz]/[organisation]/[user]/preview/page.js
Ich würde den Teilnehmen Button mindestens disablen, wenn nicht sogar ganz ausblenden.

Der Foto-Upload-Button kann in der Preview auch raus.

Die Preview mal mit einem Deutlich längeren Text testen, schauen wie und wo da die Scrollbar erscheint.

2024-12-12 21:37 UTC, Mac10goesBRRRT commented on app/[instanz]/[organisation]/[user]/editEvent/page.js
Der Image Placeholder ist Breit aber nicht hoch. 16:9 Bilder lassen sich so schwerer sinnvoll einfügen. Wie ist hier der Plan? Sollte dem User hier eine Aspect-Ratio empfohlen werden?

2024-12-13 17:18 UTC, DHaytham commented
> Beide Seiten sind meiner Meinung nach evtl besser in _/event/[event-id]/editEvent_ bzw. _/event/[event-id]/preview_ aufgehoben

es gibt noch andere event ordner wie z.B createEvent, myevent und meinEntwurf soll ich dafuer dasselbe machen ?

2024-12-13 17:31 UTC, DHaytham commented on app/[instanz]/[organisation]/[user]/preview/page.js
>                      Bearbeiten
done soll jz funktionieren.

2024-12-13 17:35 UTC, DHaytham commented on app/[instanz]/[organisation]/[user]/preview/page.js
- Habe den Teilnehmer und den Foto-Upload Buttons  ausgeblendet
- Mit längeren Text auf die Preview wird die ganze Seite laenger was meinen meinung nach gut aussieht.

2024-12-13 18:06 UTC, Mac10goesBRRRT commented
> > Beide Seiten sind meiner Meinung nach evtl besser in _/event/[event-id]/editEvent_ bzw. _/event/[event-id]/preview_ aufgehoben
> 
> es gibt noch andere event ordner wie z.B createEvent, myevent und meinEntwurf soll ich dafuer dasselbe machen ?

In dem Pullrequest nicht, das kann aber in nem extra Pull-Request gemacht werden. In dem hier nur die Dateien, die schon drin sind.

2024-12-13 18:10 UTC, Mac10goesBRRRT commented on app/[instanz]/[organisation]/[user]/preview/page.js
>                      Bearbeiten
hast du noch mal commits gepusht? Seh bei mir noch nichts

2024-12-13 19:21 UTC, DHaytham commented on app/[instanz]/[organisation]/[user]/preview/page.js
>                      Bearbeiten
musste noch kleinigkeiten bearbeiten, jz kannst du dir es ansehen.

2024-12-13 19:22 UTC, DHaytham commented on app/[instanz]/[organisation]/[user]/editEvent/page.js
soll jz funktionieren .

2024-12-13 21:30 UTC, CeloKr commented
Meine Meinung: 
myEvent, createEvent etc was man selbst erstellt, soll in der Sturktur bleiben wie wir es haben. Wenn ein Event angelegt wird soll diese unter event/[event_id] angezeigt werden. 

Wie könnte man da drauf? 
z.B. im Terminmanagement auf ein Termin klicken und Termin Details anzeigen, kommt auf auf event/[event_id]

--> Unter myEvent wird man ja nur sehen, welche Veranstaltungen man erstellt hat, diese kann ruhig auf der route /intanz/organisation/user/myEvent bleiben. 

--> wenn ich als Teilnehmer bzw. später auf Meine Teilnahmen klicke, werde ich ja eine Liste an meine Teilnahmen sehen. 
Da könnte man z.b. auch auf Details anzeigen klicken und man kommt auf die Route --> /event/[event_id]. 

so wäre es meiner meinung nach sehr sinnvoll.

2024-12-13 21:33 UTC, Mac10goesBRRRT commented on app/[instanz]/[organisation]/[user]/editEvent/page.js
> +            }}
@CeloKr Schau mal, ob du hier was entsprechendes gebaut hast.

2024-12-13 21:33 UTC, Mac10goesBRRRT commented on app/[instanz]/[organisation]/[user]/preview/page.js
Jo, das schon mal gut!

2024-12-13 21:37 UTC, Mac10goesBRRRT commented
> Meine Meinung: myEvent, createEvent etc was man selbst erstellt, soll in der Sturktur bleiben wie wir es haben. Wenn ein Event angelegt wird soll diese unter event/[event_id] angezeigt werden.
> 
> Wie könnte man da drauf? z.B. im Terminmanagement auf ein Termin klicken und Termin Details anzeigen, kommt auf auf event/[event_id]
> 
> --> Unter myEvent wird man ja nur sehen, welche Veranstaltungen man erstellt hat, diese kann ruhig auf der route /intanz/organisation/user/myEvent bleiben.
> 
> --> wenn ich als Teilnehmer bzw. später auf Meine Teilnahmen klicke, werde ich ja eine Liste an meine Teilnahmen sehen. Da könnte man z.b. auch auf Details anzeigen klicken und man kommt auf die Route --> /event/[event_id].
> 
> so wäre es meiner meinung nach sehr sinnvoll.

Also das wäre kein Problem, du machst im backend den Fetch ja sowieso über die id. Dann wäre die ID der ausschlaggebende Punkt, auch weil in einer Orga ja nicht zwingend ich als Mitglied die Veranstaltung erstelle oder editiere.

Myevent würde ich als fetch nutzen um alle meine Events ziehen zu können.

2024-12-13 22:21 UTC, CeloKr commented
Also meinst du Meine Teilnahmen komplett weg lassen und nur über Meine Veranstaltungen machen?

2025-02-07 13:40 UTC, closed without merging