add multi-language
HSFD-WS-24-25/appointment-organizer-frontend pull request #86
Opened 2024-12-16 13:56 UTC by marvinrentsch

Hiermit wird das Grundgerüst für die Mehrsprachigkeit implementiert. #85 

Die Mehrsprachigkeit wurde mit next-intl mit der folgenden Anleitung implementiert und an unser Projekt angepasst: https://next-intl.dev/docs/getting-started/app-router/with-i18n-routing

Damit es funktioniert, muss die next-intl-Bibliothek installiert werden:
npm install next-intl

Wichtig: Damit das Routing für die Mehrsprachigkeit funktioniert, wurden alle Dateien innerhalb des app-Orders einen Ordner tiefer in den [locale]-Ordner verschoben.
Also app/... wird zu app/[locale]/...
Deswegen wurden auch so viele Dateien geändert.

Changelog:
Alle Dateien innerhalb des app-Ordners wurden einen Ordner tiefer in den [locale]-Ordner verschoben. Also app/... wird zu app/[locale]/...

Im app-Ordner wurde in der Datei layout.js die RootLayout-Funktion auf async gesetzt, damit unter anderem gewartet wird, bis die Übersetzungen geladen wurden. Außerdem wurde next-intl und der NextIntlClientProvider hinzugefügt, damit die Übersetzungen auch funktionieren.

Im components-Ordner wurden die Dateien LocaleSwitcher.js und LocaleSwitcherSelect.js hinzugefügt, welche das Ändern der Sprache mit einem Select hinzufügt.

Im Hauptverzeichnis wurde die Datei next.config.mjs das notwendige next-intl-Plugin integriert.

Im Hauptverzeichnis wurde der Ordner messages hinzugefügt, mit den Dateien de.json und en.json, welche die Übersetzungen für die jeweilige Sprache beinhalten.

Im Hauptverzeichnis wurde der Ordner i18n hinzugefügt, mit den Dateien request.ts und routing.ts, welche sich um das Weiterleiten kümmert.

Im Hauptverzeichnis wurde die Datei middleware.ts hinzugefügt, welche sich um das Weiterleiten auf die richtige Sprache kümmert.

Die Einstellungsseite wurde überarbeitet, sodass jetzt hier per Select die Sprache ausgewählt werden kann. Außerdem ist als Standard immer die Sprache ausgewählt, mit der die Seite aufgerufen wurde.
Die Einstellungseite wurde auch direkt übersetzt.

2024-12-16 14:34 UTC, EricBergstreisser commented
Also bei mir geht es noch nicht ganz. Die Seiten sind alle noch nicht über die Buttons aufrufbar. Ich muss in der URL immer ein /de/ per Hand einfügen. Meintest du das damit, dass du gesagt hast du willst danach noch was anpassen?
Wenn ja, dann würde ich vielleicht den Dev-Branch duplizieren und auf den mergen, um keine Konflikte zu haben.

Die Einstellungen Seite ist bei mir nicht da.

Fällt euch eine Lösung ein, dass wir bei den Buttons nicht immer die gesamte Route angeben müssen? Weil wenn wir einen Überordner erzeugen, wie in diesem Feature, dann müssen wir wie gesagt überall die Route anpassen.

Gibt es dafür nicht sowas wie Router oder so?

2024-12-16 14:41 UTC, Mac10goesBRRRT commented
@marvinrentsch kannst du das morgen noch mal genau erklären? Wirkt auf mich recht komplex, aber auch nötig. Ich werde es mir später auf jedenfall auch noch mal anschauen und alles testen.


@EricBergstreisser 
> Fällt euch eine Lösung ein, dass wir bei den Buttons nicht immer die gesamte Route angeben müssen? Weil wenn wir einen Überordner erzeugen, wie in diesem Feature, dann müssen wir wie gesagt überall die Route anpassen.
> 
> Gibt es dafür nicht sowas wie Router oder so?

Können die in root entsprechend was mit "@/[locale]/..." bauen, das macht es einfacher. Quasi eine Erweiterung von dem, was in #84 angefangen wurde.

2024-12-16 14:52 UTC, marvinrentsch commented
> Also bei mir geht es noch nicht ganz. Die Seiten sind alle noch nicht über die Buttons aufrufbar. Ich muss in der URL immer ein /de/ per Hand einfügen. Meintest du das damit, dass du gesagt hast du willst danach noch was anpassen?
> Wenn ja, dann würde ich vielleicht den Dev-Branch duplizieren und auf den mergen, um keine Konflikte zu haben.

Ja genau. Man müsste in einen Styled Button wie GreenButton oder so das Link Element mit dem Pfad einfügen und next-intl fügt je nachdem welche Sprache gerade aktiv ist de oder en an die URL an.
<GreenButton>
<Link href="/instanz/organisation/user/settings">Einstellungen</Link>
</GreenButton>
Dieser Link würde dann zu "de/instanz/organisation/user/settings" weiterleiten, wenn Deutsch die aktuelle Sprache ist.

> Die Einstellungen Seite ist bei mir nicht da.

Die Einstellungen sollten eigentlich mit http://localhost:3000/de/instanz/organisation/user/settings aufrufbar sein.

> @marvinrentsch kannst du das morgen noch mal genau erklären? Wirkt auf mich recht komplex, aber auch nötig. Ich werde es mir später auf jedenfall auch noch mal anschauen und alles testen.

Ja, kann ich machen. Es ist recht komplett, weil wir es halt mittendrin hinzufügen. Aber im Prinzip habe ich nur ein paar Dateien hinzugefügt bzw. angepasst und den Inhalt des App-Ordners eine Ebene tiefer gemacht, weil dort dann de oder en der URL steht.

2024-12-17 00:16 UTC, CeloKr commented
An sich genau richtig. 
Jedoch muss es verfeinert und angepasst werden. 
Punkt 1 --> Sidebar wird nicht übersetzt 
Punkt 2 --> middleware.ts kann mit middleware.js kombiniert werden. 

dann würde ich es besser sein wenn messages in den components ordner reinkommt, damit wirklich alles woran man änderungen vornimmt in components drin ist. am besten components/messages oder besser components/translation oder ähnliches. 

@EricBergstreisser
um die Imports so zu organisieren, dass die redunanz verbessert könnte man folgendes machen: 
Alle imports die bei den jeweiligen page.js dateien vorhanden ist, in eine seperate datei z.b. imports.js erstellen, diese dann mit in die hauptdatei (layout.js) einbinden. 
Würde pro Datei 5 - 8 Zeilen code verschwinden / wenn nicht sogar alle imports. 
 

ich würde diese pullrequest soweit offen lassen, bis es einwandfrei funktioniert. 

bitte weiter dran arbeiten. 
dennoch gute arbeit

2024-12-17 16:53 UTC, marvinrentsch commented
> Also bei mir geht es noch nicht ganz. Die Seiten sind alle noch nicht über die Buttons aufrufbar. Ich muss in der URL immer ein /de/ per Hand einfügen. Meintest du das damit, dass du gesagt hast du willst danach noch was anpassen?

Das geht indem man useRouter von next-intl, statt von next navigation importiert.
```
import { useRouter } from '@/i18n/routing';
```
statt
```
import { useRouter } from 'next/navigation';
```
Dann wird automatisch "/de" oder "/en" in der (dynamischen) URL hinzugefügt.
```
router.push(`${basePath}`);
```

2024-12-19 16:06 UTC, EricBergstreisser submitted a review, later dismissed
Großes aber sinnvolles Feature. Bitte trotzdem noch das Backlog-Item als Issue hinzufügen und ein neues Item bzw. Issue erstellen, welches die weiteren Schritte beschreibt. Vor allem als erstes Issue müssen die Routen angepasst werden, auf welche die Buttons führen.

2024-12-19 16:48 UTC, Mac10goesBRRRT commented
> > Also bei mir geht es noch nicht ganz. Die Seiten sind alle noch nicht über die Buttons aufrufbar. Ich muss in der URL immer ein /de/ per Hand einfügen. Meintest du das damit, dass du gesagt hast du willst danach noch was anpassen?
> 
> Das geht indem man useRouter von next-intl, statt von next navigation importiert.
> 
> ```
> import { useRouter } from '@/i18n/routing';
> ```
> 
> statt
> 
> ```
> import { useRouter } from 'next/navigation';
> ```
> 
> Dann wird bei `router.push` automatisch "/de" oder "/en" in der (dynamischen) URL hinzugefügt.
> 
> ```
> router.push(`${basePath}`);
> ```
> 
> Das würde ich dann hinzufügen, wenn ich die Übersetzungen in die einzelnen Seiten hinzufüge.

Das heist, wir müssen hier noch mal alle Pages entsprechend abändern?

2025-01-11 14:25 UTC, marvinrentsch commented
> Das heist, wir müssen hier noch mal alle Pages entsprechend abändern?

Ja. Sofern router.push verwendet wurde, muss man nur den Import abändern.

Der Fallback ist jetzt eingerichtet. Wenn bei Deutsch eine Übersetzung fehlt, wird die Englische Übersetzung angezeigt.

2025-01-11 14:26 UTC, marvinrentsch commented
> Das heist, wir müssen hier noch mal alle Pages entsprechend abändern?

Ja. Sofern router.push verwendet wurde, muss man nur den Import abändern.

Der Fallback ist jetzt eingerichtet #88. 

Wenn bei Deutsch eine Übersetzung fehlt, wird die Englische Übersetzung angezeigt.

2025-01-23 19:13 UTC, EricBergstreisser commented
Kannst du schauen, ob du die Konflikte behoben bekommst? Dann können wir es direkt danach mergen.

2025-01-24 16:38 UTC, marvinrentsch commented
Ich habe jetzt die Konflikte behoben.

Nach dem mergen würde ich dann die Imports anpassen, damit die Buttons wieder richtig weiterleiten und die Übersetzungen einfügen.

2025-01-27 15:09 UTC, EricBergstreisser approved these changes
Sollte jetzt ohne Konflikte gehen.

2025-01-27 15:19 UTC, marvinrentsch commented
Ich bin jetzt gerade noch dabei die Übersetzungen einzufügen. Danach kann es dann gemerged werden.

2025-01-28 11:16 UTC, marvinrentsch commented
Die Übersetzungen sind jetzt eingefügt. Es sollte jetzt alles gehen.

2025-02-03 11:04 UTC, marvinrentsch commented
Könnt ihr das dann mergen, wenn das so passt?

2025-02-03 11:12 UTC, marvinrentsch commented
Kann ich das dann mergen?

2025-02-03 19:14 UTC, CeloKr commented
Bitte erst Login funktionsfähig machen..

2025-02-04 16:04 UTC, EricBergstreisser requested changes
Fix login

2025-02-06 07:14 UTC, CeloKr approved these changes
Alle Fehler wurden, die seiten funktionieren einwandfrei. 
Die übersetzung für das gerüst des apps läuft. 

Von meiner seite aus ist alles in ordnung

2025-02-06 16:21 UTC, Mac10goesBRRRT approved these changes
Ich hab hier nicht alles 100% reviewed, aber das was ich gesehen habe, lief.

2025-02-06 16:24 UTC, EricBergstreisser approved these changes

2025-02-06 16:24 UTC, merged