change needed approvals
HSFD-WS-24-25/appointment-organizer-frontend pull request #87
Opened 2024-12-17 13:55 UTC by EricBergstreisser

Es wurde eine Github Action hinzugefügt.
Wenn 10 oder mehr Dateien in einem Pull Request geändert wurden, dann müssen mindestens zwei Reviewer ihr Approval geben.
Die Anzahlen können im Code recht einfach geändert werden, wenn wir von 10 auf 15 oder so erhöhen wollen.

Diese Action muss in Rules in den Einstellungen vom Repository nicht direkt eingebunden werden, da sie sich selbst triggert. Es muss jedoch eingestellt sein, dass die Checks erfolgreich sein müssen.

2024-12-17 13:56 UTC, EricBergstreisser commented
Da es eine Action ist, kann man die schwer testen. Konnte jetzt sehen, dass noch was fehlt und geändert werden muss.

2024-12-17 14:53 UTC, Mac10goesBRRRT commented
Warum failt das denn jetzt? Warum failt das beim öffnen? Finde ich ungeschickt, gibt da nicht ne andere Möglichkeit? Prinzipiell finde ich das sinnvoll, wenn mehr leute drüber schauen, aber meiner Meinung nach haste hier mitunter einfach Probleme, wenn du die Struktur von Komponenten oder so änderst

2024-12-17 15:13 UTC, Mac10goesBRRRT requested changes

2024-12-17 15:13 UTC, Mac10goesBRRRT commented on .github/workflows/enforceDynamicApprovals.yml
> +    types:
Nur on review ausführen

2024-12-19 11:01 UTC, Mac10goesBRRRT approved these changes
Passt jetzt.

2024-12-19 11:43 UTC, merged